import type { Topic } from './interpreter-topics';

/**
 * ASSUNTOS DE TERRITÓRIO E DE FUTURO: REGIÃO, AGRO, AMBIENTE, ENERGIA E TECNOLOGIA
 *
 * Terceiro bloco do catálogo. Mesma regra dos outros dois: toda entrada tem
 * perdedor, e a direção contrária inverte todos os sinais.
 *
 * O que estas entradas têm de diferente é o PRAZO. Reserva estratégica, usina
 * nuclear, irrigação, semicondutor e satélite não entregam nada dentro de um
 * mandato — entregam depois, e cobram durante. Por isso a maior parte delas tem
 * custo alto, efeito imediato pequeno e ganho que aparece no `delayedEffects`
 * montado pelo interpretador. É o tipo de decisão em que o presidente planta o
 * que outro colhe, e o jogo precisa deixar isso visível.
 */
export const FUTURO_TOPICS: readonly Topic[] = [
  // -------------------------------------------------------------------------
  // Desenvolvimento regional
  // -------------------------------------------------------------------------
  {
    id: 'desenvolvimento_regional',
    specificity: 1.8,
    keywords: [
      'zonas especiais de desenvolvimento', 'zona de processamento', 'desenvolvimento regional',
      'cidades pequenas', 'cidades de fronteira', 'semiarido', 'regioes pobres', 'interior do pais',
      'municipios pobres', 'incentivo para empresas se instalarem',
    ],
    category: 'economia',
    ministries: ['fazenda', 'infraestrutura'],
    baseCost: 20e9,
    instrument: 'projeto_lei',
    legalRisk: 22,
    months: 30,
    label: 'desenvolvimento regional',
    expand: {
      primaryBalance: -20,
      gdpGrowth: 0.12,
      unemployment: -0.16,
      poverty: -0.4,
      fiscalCredibility: -2.4,
    },
    winners: [
      { groupId: 'baixa_renda', delta: 3, reason: 'Emprego formal onde só havia informalidade.' },
      { groupId: 'empresariado', delta: 2.4, reason: 'Incentivo fiscal para instalar planta longe do eixo.' },
      { groupId: 'trabalhadores', delta: 1.8, reason: 'Vaga perto de casa em vez de migração forçada.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -2.6, reason: 'Renúncia fiscal regional raramente é revogada depois.' },
      { groupId: 'classe_media', delta: -1, reason: 'Benefício concentrado numa região é imposto pago por todas.' },
    ],
  },
  {
    id: 'desenvolvimento_amazonia',
    specificity: 2,
    keywords: ['amazonia', 'floresta amazonica', 'bioeconomia', 'desenvolvimento da amazonia'],
    category: 'meio_ambiente',
    ministries: ['infraestrutura', 'agricultura'],
    baseCost: 24e9,
    instrument: 'programa',
    legalRisk: 24,
    months: 36,
    label: 'desenvolvimento sustentável da Amazônia',
    expand: {
      primaryBalance: -24,
      environmentIndex: 1.8,
      poverty: -0.4,
      gdpGrowth: 0.07,
    },
    winners: [
      { groupId: 'indigenas', delta: 3.4, reason: 'Política de território com dinheiro atrás.' },
      { groupId: 'ambientalistas', delta: 3, reason: 'Floresta em pé valendo mais do que derrubada.' },
      { groupId: 'baixa_renda', delta: 1.8, reason: 'Renda na floresta sem precisar desmatar.' },
    ],
    losers: [
      { groupId: 'agronegocio', delta: -2.4, reason: 'Mais restrição de uso da terra na fronteira agrícola.' },
      { groupId: 'mercado_financeiro', delta: -1.6, reason: 'Programa caro com retorno difícil de medir.' },
    ],
  },
  {
    id: 'fundo_municipios',
    specificity: 1.9,
    keywords: [
      'fundo de desenvolvimento para municipios', 'repasse para municipios', 'fundo de participacao',
      'ajudar prefeituras',
    ],
    category: 'institucional',
    ministries: ['fazenda', 'casa_civil'],
    baseCost: 28e9,
    instrument: 'projeto_lei',
    legalRisk: 20,
    months: 24,
    label: 'transferência para municípios pobres',
    expand: {
      primaryBalance: -28,
      poverty: -0.5,
      healthIndex: 0.7,
      educationIndex: 0.7,
      fiscalCredibility: -3,
      approval: 1.4,
    },
    winners: [
      { groupId: 'baixa_renda', delta: 2.8, reason: 'Prefeitura pequena é quem entrega saúde e escola na ponta.' },
      { groupId: 'servidores', delta: 1.6, reason: 'Folha municipal deixa de atrasar.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -3, reason: 'Transferência constitucional nova, sem contrapartida de gestão.' },
      { groupId: 'classe_media', delta: -1.2, reason: 'Dinheiro repassado sem controle de quem recebe.' },
    ],
  },
  {
    id: 'medicos_interior',
    specificity: 2,
    keywords: [
      'medicos especialistas', 'medicos nas regioes remotas', 'medicos no interior',
      'levar medicos', 'atendimento em regioes remotas',
    ],
    category: 'saude',
    ministries: ['saude'],
    baseCost: 11e9,
    instrument: 'programa',
    legalRisk: 18,
    months: 24,
    label: 'médicos para regiões remotas',
    expand: {
      primaryBalance: -11,
      healthIndex: 1.6,
      lifeExpectancy: 0.1,
      poverty: -0.15,
      approval: 1.6,
    },
    winners: [
      { groupId: 'baixa_renda', delta: 3.6, reason: 'Consulta que hoje exige viajar 300 quilômetros.' },
      { groupId: 'indigenas', delta: 2.4, reason: 'Atendimento chegando onde nunca chegou.' },
    ],
    losers: [
      { groupId: 'universitarios', delta: -1.6, reason: 'Categoria médica reage a programa que traz profissional de fora.' },
      { groupId: 'mercado_financeiro', delta: -1.2, reason: 'Custo por atendimento em região remota é alto e permanente.' },
    ],
  },
  {
    id: 'polos_tecnologicos',
    specificity: 1.9,
    keywords: ['polos tecnologicos', 'parque tecnologico', 'polo de inovacao', 'fora das capitais'],
    category: 'economia',
    ministries: ['infraestrutura', 'educacao'],
    baseCost: 13e9,
    instrument: 'programa',
    legalRisk: 18,
    months: 30,
    label: 'polos tecnológicos regionais',
    expand: {
      primaryBalance: -13,
      gdpGrowth: 0.09,
      educationIndex: 0.6,
      businessConfidence: 2,
      unemployment: -0.06,
    },
    winners: [
      { groupId: 'universitarios', delta: 3, reason: 'Emprego qualificado sem precisar mudar de estado.' },
      { groupId: 'empresariado', delta: 2, reason: 'Mão de obra técnica formada perto da operação.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -1.8, reason: 'Polo tecnológico é aposta de longo prazo com dinheiro público.' },
      { groupId: 'baixa_renda', delta: -0.8, reason: 'O emprego criado exige formação que eles não têm.' },
    ],
  },

  // -------------------------------------------------------------------------
  // Agricultura e alimentos
  // -------------------------------------------------------------------------
  {
    id: 'estoque_estrategico_alimentos',
    specificity: 2,
    keywords: [
      'estoques estrategicos', 'estoque regulador', 'estoque publico de alimentos',
      'reserva de alimentos',
    ],
    category: 'agricultura',
    ministries: ['agricultura', 'fazenda'],
    baseCost: 15e9,
    instrument: 'medida_provisoria',
    legalRisk: 18,
    months: 18,
    label: 'estoques estratégicos de alimentos',
    expand: {
      primaryBalance: -15,
      inflation: -0.16,
      poverty: -0.2,
      approval: 1,
    },
    winners: [
      { groupId: 'baixa_renda', delta: 2.6, reason: 'Preço do arroz e do feijão para de disparar na entressafra.' },
      { groupId: 'agronegocio', delta: 1.6, reason: 'Governo comprando quando o preço desaba.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -2.4, reason: 'Estoque público custa armazenagem e distorce preço.' },
      { groupId: 'empresariado', delta: -1.2, reason: 'Atacado perde a margem que ganhava na oscilação.' },
    ],
  },
  {
    id: 'irrigacao',
    specificity: 1.9,
    keywords: ['irrigacao', 'canal de irrigacao', 'transposicao', 'perimetro irrigado'],
    category: 'agricultura',
    ministries: ['agricultura', 'infraestrutura'],
    baseCost: 22e9,
    instrument: 'programa',
    legalRisk: 22,
    months: 36,
    label: 'infraestrutura de irrigação',
    expand: {
      primaryBalance: -22,
      gdpGrowth: 0.1,
      infrastructureIndex: 1.2,
      poverty: -0.25,
      environmentIndex: -0.7,
    },
    winners: [
      { groupId: 'agronegocio', delta: 3.4, reason: 'Duas safras onde só cabia uma.' },
      { groupId: 'baixa_renda', delta: 1.8, reason: 'Emprego rural no semiárido durante e depois da obra.' },
    ],
    losers: [
      { groupId: 'ambientalistas', delta: -2.6, reason: 'Uso intensivo de água em bacia que já está no limite.' },
      { groupId: 'mercado_financeiro', delta: -2, reason: 'Obra longa, cara e com histórico de atraso.' },
    ],
  },
  {
    id: 'armazenagem_graos',
    specificity: 2,
    keywords: ['armazenamento de graos', 'silos', 'armazenagem da safra', 'capacidade de armazenagem'],
    category: 'agricultura',
    ministries: ['agricultura'],
    baseCost: 10e9,
    instrument: 'programa',
    legalRisk: 14,
    months: 24,
    label: 'armazenagem de grãos',
    expand: {
      primaryBalance: -10,
      inflation: -0.08,
      infrastructureIndex: 0.7,
      gdpGrowth: 0.05,
    },
    winners: [
      { groupId: 'agronegocio', delta: 3.2, reason: 'Produtor deixa de vender na colheita pelo pior preço do ano.' },
      { groupId: 'caminhoneiros', delta: 1.4, reason: 'Frete distribuído no ano em vez de concentrado na safra.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -1.8, reason: 'Subsídio a ativo privado com retorno para o dono do silo.' },
      { groupId: 'empresariado', delta: -1, reason: 'Trading perde poder de barganha na hora da colheita.' },
    ],
  },
  {
    id: 'seguro_rural',
    specificity: 2.1,
    keywords: [
      'seguro rural', 'seguro contra seca', 'seguro contra enchente', 'seguro agricola',
      'subvencao ao seguro', 'seguro para agricultores',
    ],
    category: 'agricultura',
    ministries: ['agricultura', 'fazenda'],
    baseCost: 12e9,
    instrument: 'projeto_lei',
    legalRisk: 16,
    months: 20,
    label: 'seguro rural subsidiado',
    expand: {
      primaryBalance: -12,
      inflation: -0.06,
      poverty: -0.2,
      gdpGrowth: 0.05,
    },
    winners: [
      { groupId: 'agronegocio', delta: 3.6, reason: 'Uma seca deixa de significar a perda da propriedade.' },
      { groupId: 'baixa_renda', delta: 1.6, reason: 'Pequeno agricultor é quem quebra primeiro sem seguro.' },
      { groupId: 'mercado_financeiro', delta: 1.2, reason: 'Crédito rural com risco climático coberto é crédito mais barato.' },
    ],
    losers: [
      { groupId: 'classe_media', delta: -1.2, reason: 'O prêmio do seguro privado é pago com dinheiro público.' },
      { groupId: 'ambientalistas', delta: -1.4, reason: 'Seguro barato incentiva plantar onde não se deveria plantar.' },
    ],
  },
  {
    id: 'desperdicio_alimentos',
    specificity: 2,
    keywords: ['desperdicio de alimentos', 'perda de alimentos', 'banco de alimentos', 'doacao de alimentos'],
    category: 'social',
    ministries: ['agricultura', 'desenvolvimento_social'],
    baseCost: 4e9,
    instrument: 'projeto_lei',
    legalRisk: 14,
    months: 18,
    label: 'combate ao desperdício de alimentos',
    expand: {
      primaryBalance: -4,
      poverty: -0.3,
      environmentIndex: 0.6,
      inflation: -0.04,
      approval: 0.9,
    },
    winners: [
      { groupId: 'baixa_renda', delta: 2.6, reason: 'Comida que ia para o lixo chega à mesa.' },
      { groupId: 'ambientalistas', delta: 2, reason: 'Menos produção jogada fora é menos pressão sobre a terra.' },
    ],
    losers: [
      { groupId: 'empresariado', delta: -1.6, reason: 'Varejo e indústria passam a responder pelo que descartam.' },
    ],
  },
  {
    id: 'corredores_logisticos',
    specificity: 1.8,
    keywords: [
      'corredores de transporte', 'escoamento da safra', 'corredor logistico',
      'transporte de produtos agricolas',
    ],
    category: 'infraestrutura',
    ministries: ['infraestrutura', 'agricultura'],
    baseCost: 32e9,
    instrument: 'programa',
    legalRisk: 22,
    months: 42,
    label: 'corredores logísticos do agronegócio',
    expand: {
      primaryBalance: -32,
      infrastructureIndex: 1.8,
      gdpGrowth: 0.14,
      inflation: -0.06,
    },
    winners: [
      { groupId: 'agronegocio', delta: 3.4, reason: 'Frete menor por tonelada até o porto.' },
      { groupId: 'caminhoneiros', delta: 1.6, reason: 'Estrada melhor e menos tempo parado na fila.' },
      { groupId: 'empresariado', delta: 1.8, reason: 'Custo logístico é o que tira competitividade do produto brasileiro.' },
    ],
    losers: [
      { groupId: 'ambientalistas', delta: -2.4, reason: 'Corredor logístico abre a fronteira agrícola junto.' },
      { groupId: 'indigenas', delta: -1.8, reason: 'Traçado costuma passar perto de terra demarcada.' },
    ],
  },
  {
    id: 'banco_sementes',
    specificity: 2.2,
    keywords: ['banco de sementes', 'germoplasma', 'sementes crioulas', 'banco publico de sementes'],
    category: 'agricultura',
    ministries: ['agricultura'],
    baseCost: 2.5e9,
    instrument: 'programa',
    legalRisk: 12,
    months: 24,
    label: 'banco público de sementes',
    expand: {
      primaryBalance: -2.5,
      environmentIndex: 0.9,
      gdpGrowth: 0.04,
    },
    winners: [
      { groupId: 'agronegocio', delta: 1.8, reason: 'Material genético nacional reduz dependência de fornecedor externo.' },
      { groupId: 'universitarios', delta: 1.8, reason: 'Pesquisa agrícola com base própria.' },
      { groupId: 'indigenas', delta: 1.4, reason: 'Variedades tradicionais preservadas e reconhecidas.' },
    ],
    losers: [
      { groupId: 'empresariado', delta: -1.6, reason: 'Semente pública concorre com semente patenteada.' },
    ],
  },

  // -------------------------------------------------------------------------
  // Meio ambiente
  // -------------------------------------------------------------------------
  {
    id: 'servicos_ambientais',
    specificity: 2.1,
    keywords: [
      'floresta em pe', 'pagamento por servicos ambientais', 'preservarem florestas',
      'pagar quem preserva', 'quem preservar', 'credito de conservacao',
    ],
    category: 'meio_ambiente',
    ministries: ['agricultura', 'fazenda'],
    baseCost: 16e9,
    instrument: 'projeto_lei',
    legalRisk: 18,
    months: 30,
    label: 'pagamento por serviços ambientais',
    expand: {
      primaryBalance: -16,
      environmentIndex: 2,
      poverty: -0.2,
      approval: 0.8,
    },
    winners: [
      { groupId: 'ambientalistas', delta: 3.4, reason: 'Floresta em pé passa a render mais que floresta derrubada.' },
      { groupId: 'indigenas', delta: 2.6, reason: 'Quem sempre preservou passa a receber por isso.' },
      { groupId: 'baixa_renda', delta: 1.6, reason: 'Renda para pequeno proprietário e ribeirinho.' },
    ],
    losers: [
      { groupId: 'agronegocio', delta: -2.2, reason: 'Terra parada com pagamento público encarece a expansão da lavoura.' },
      { groupId: 'mercado_financeiro', delta: -1.8, reason: 'Despesa nova e permanente por um resultado difícil de auditar.' },
    ],
  },
  {
    id: 'reciclagem',
    specificity: 1.9,
    keywords: ['reciclagem', 'coleta seletiva', 'catadores', 'residuos solidos'],
    category: 'meio_ambiente',
    ministries: ['infraestrutura'],
    baseCost: 8e9,
    instrument: 'programa',
    legalRisk: 14,
    months: 24,
    label: 'reciclagem e resíduos sólidos',
    expand: {
      primaryBalance: -8,
      environmentIndex: 1.7,
      sanitationIndex: 0.9,
      healthIndex: 0.3,
    },
    winners: [
      { groupId: 'ambientalistas', delta: 3.2, reason: 'Lixão fechado é a pauta ambiental mais concreta que existe.' },
      { groupId: 'baixa_renda', delta: 2.2, reason: 'Catador organizado em cooperativa ganha mais e com segurança.' },
    ],
    losers: [
      { groupId: 'empresariado', delta: -1.8, reason: 'Logística reversa vira obrigação de quem produz a embalagem.' },
    ],
  },
  {
    id: 'plastico_descartavel',
    specificity: 2,
    keywords: ['plasticos descartaveis', 'plastico de uso unico', 'proibir plastico', 'canudo de plastico'],
    category: 'meio_ambiente',
    ministries: ['infraestrutura'],
    baseCost: 1.5e9,
    instrument: 'projeto_lei',
    legalRisk: 22,
    months: 24,
    label: 'restrição a plásticos descartáveis',
    expand: {
      primaryBalance: -1.5,
      environmentIndex: 1.5,
      sanitationIndex: 0.4,
      businessConfidence: -1.4,
    },
    winners: [
      { groupId: 'ambientalistas', delta: 3.6, reason: 'Menos plástico no rio e no mar, com prazo definido.' },
      { groupId: 'universitarios', delta: 1.4, reason: 'Pauta ambiental com efeito visível no dia a dia.' },
    ],
    losers: [
      { groupId: 'empresariado', delta: -2.6, reason: 'Indústria de embalagem tem de trocar linha de produção inteira.' },
      { groupId: 'classe_media', delta: -1, reason: 'O substituto custa mais caro e funciona pior.' },
    ],
  },
  {
    id: 'economia_circular',
    specificity: 1.9,
    keywords: ['residuos industriais', 'economia circular', 'reutilizar residuos', 'reaproveitamento industrial'],
    category: 'meio_ambiente',
    ministries: ['infraestrutura', 'fazenda'],
    baseCost: 6e9,
    instrument: 'projeto_lei',
    legalRisk: 18,
    months: 24,
    label: 'economia circular na indústria',
    expand: {
      primaryBalance: -6,
      environmentIndex: 1.3,
      gdpGrowth: 0.05,
      businessConfidence: 1,
    },
    winners: [
      { groupId: 'ambientalistas', delta: 2.4, reason: 'Resíduo vira insumo em vez de aterro.' },
      { groupId: 'empresariado', delta: 1.6, reason: 'Incentivo fiscal para quem reaproveita o próprio rejeito.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -1.4, reason: 'Mais uma renúncia fiscal setorial sem prazo de validade.' },
    ],
  },
  {
    id: 'monitoramento_rios',
    specificity: 2,
    keywords: ['monitoramento de rios', 'qualidade da agua', 'bacias hidrograficas', 'poluicao dos rios'],
    category: 'meio_ambiente',
    ministries: ['infraestrutura'],
    baseCost: 5e9,
    instrument: 'programa',
    legalRisk: 14,
    months: 24,
    label: 'monitoramento de rios e bacias',
    expand: {
      primaryBalance: -5,
      environmentIndex: 1.2,
      sanitationIndex: 1,
      healthIndex: 0.5,
    },
    winners: [
      { groupId: 'ambientalistas', delta: 2.8, reason: 'Dado público sobre quem está poluindo e onde.' },
      { groupId: 'baixa_renda', delta: 1.6, reason: 'Quem bebe água de rio contaminado é quem mora perto dele.' },
    ],
    losers: [
      { groupId: 'agronegocio', delta: -1.8, reason: 'Monitorar bacia é monitorar uso de agrotóxico e de água.' },
      { groupId: 'empresariado', delta: -1.4, reason: 'Indústria passa a ter lançamento medido em tempo real.' },
    ],
  },
  {
    id: 'defesa_civil',
    specificity: 1.9,
    keywords: [
      'desastres climaticos', 'alerta de enchentes', 'deslizamentos', 'defesa civil',
      'prevencao de desastres', 'areas de risco',
    ],
    category: 'infraestrutura',
    ministries: ['infraestrutura', 'justica'],
    baseCost: 13e9,
    instrument: 'programa',
    legalRisk: 14,
    months: 24,
    label: 'prevenção de desastres climáticos',
    expand: {
      primaryBalance: -13,
      securityIndex: 0.9,
      environmentIndex: 0.8,
      infrastructureIndex: 0.9,
      approval: 1.6,
    },
    winners: [
      { groupId: 'baixa_renda', delta: 3.2, reason: 'Quem mora em área de risco é quem morre na enchente.' },
      { groupId: 'ambientalistas', delta: 2, reason: 'Adaptação climática saindo do discurso.' },
      { groupId: 'policiais', delta: 1.2, reason: 'Resgate com estrutura em vez de improviso.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -1.8, reason: 'Gasto preventivo não aparece em indicador nenhum enquanto funciona.' },
      { groupId: 'empresariado', delta: -1, reason: 'Restrição de construção em área de risco trava terreno valorizado.' },
    ],
  },

  // -------------------------------------------------------------------------
  // Energia e recursos estratégicos
  // -------------------------------------------------------------------------
  {
    id: 'reserva_estrategica',
    specificity: 2.1,
    keywords: [
      'reserva estrategica', 'estoque estrategico de petroleo', 'reserva de petroleo',
      'reserva de gas', 'minerais criticos', 'reserva nacional de combustivel',
    ],
    category: 'economia',
    ministries: ['infraestrutura', 'fazenda'],
    baseCost: 28e9,
    instrument: 'projeto_lei',
    legalRisk: 20,
    months: 30,
    label: 'reserva estratégica de energia e minerais',
    expand: {
      primaryBalance: -28,
      countryRisk: -8,
      inflation: -0.05,
      businessConfidence: 1.8,
      fiscalCredibility: -1.4,
    },
    winners: [
      { groupId: 'militares', delta: 2.8, reason: 'Autonomia energética é doutrina de segurança nacional.' },
      { groupId: 'caminhoneiros', delta: 2, reason: 'Amortecedor contra o choque de preço que para o país.' },
      { groupId: 'empresariado', delta: 1.6, reason: 'Previsibilidade de insumo em crise internacional.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -2.4, reason: 'Bilhões parados em estoque que só serve se a crise vier.' },
      { groupId: 'ambientalistas', delta: -1.8, reason: 'Estocar fóssil é apostar que ainda vamos queimar por muito tempo.' },
    ],
  },
  {
    id: 'nuclear',
    specificity: 2,
    keywords: ['energia nuclear', 'usina nuclear', 'angra', 'programa nuclear', 'usinas nucleares'],
    category: 'infraestrutura',
    ministries: ['infraestrutura', 'defesa'],
    baseCost: 62e9,
    instrument: 'projeto_lei',
    legalRisk: 30,
    months: 48,
    label: 'expansão da energia nuclear',
    expand: {
      primaryBalance: -62,
      infrastructureIndex: 1.4,
      environmentIndex: 0.5,
      gdpGrowth: 0.06,
      fiscalCredibility: -3,
    },
    winners: [
      { groupId: 'militares', delta: 3, reason: 'Domínio do ciclo do combustível é projeto de Estado para eles.' },
      { groupId: 'empresariado', delta: 1.8, reason: 'Energia de base previsível para indústria pesada.' },
      { groupId: 'universitarios', delta: 1.4, reason: 'Engenharia nuclear com programa e orçamento.' },
    ],
    losers: [
      { groupId: 'ambientalistas', delta: -3.6, reason: 'Rejeito radioativo sem destino definitivo e risco concentrado.' },
      { groupId: 'mercado_financeiro', delta: -2.6, reason: 'Obra nuclear atrasa e estoura orçamento em todo lugar do mundo.' },
    ],
  },
  {
    id: 'armazenamento_energia',
    specificity: 2,
    keywords: ['armazenamento de energia', 'baterias em rede', 'estocagem de energia', 'sistema de armazenamento'],
    category: 'infraestrutura',
    ministries: ['infraestrutura'],
    baseCost: 17e9,
    instrument: 'programa',
    legalRisk: 16,
    months: 30,
    label: 'armazenamento de energia',
    expand: {
      primaryBalance: -17,
      infrastructureIndex: 1.2,
      environmentIndex: 0.8,
      gdpGrowth: 0.06,
    },
    winners: [
      { groupId: 'ambientalistas', delta: 2.6, reason: 'Sem armazenar, sol e vento não substituem térmica.' },
      { groupId: 'empresariado', delta: 1.8, reason: 'Menos apagão e menos bandeira tarifária.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -1.8, reason: 'Tecnologia cara com curva de custo ainda caindo.' },
    ],
  },
  {
    id: 'hidrogenio_verde',
    specificity: 2.1,
    keywords: ['hidrogenio verde', 'hidrogenio de baixo carbono', 'producao de hidrogenio'],
    category: 'meio_ambiente',
    ministries: ['infraestrutura', 'fazenda'],
    baseCost: 20e9,
    instrument: 'projeto_lei',
    legalRisk: 20,
    months: 42,
    label: 'hidrogênio verde',
    expand: {
      primaryBalance: -20,
      environmentIndex: 1.4,
      gdpGrowth: 0.09,
      businessConfidence: 2,
    },
    winners: [
      { groupId: 'ambientalistas', delta: 3, reason: 'Descarbonizar a indústria pesada depende disso.' },
      { groupId: 'empresariado', delta: 2.2, reason: 'Nordeste com vento e sol vira polo exportador.' },
      { groupId: 'trabalhadores', delta: 1.4, reason: 'Emprego industrial novo onde havia pouco.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -2.2, reason: 'Subsídio grande para mercado que ainda não existe.' },
      { groupId: 'caminhoneiros', delta: -0.8, reason: 'Transição energética mira justamente o diesel.' },
    ],
  },
  {
    id: 'biocombustiveis',
    specificity: 2,
    // Radical, não a palavra inteira: "biocombustíveis" não contém
    // "biocombustivel", e o plural é como o jogador escreve.
    keywords: ['biocombustive', 'etanol de segunda geracao', 'biodiesel', 'combustivel sustentavel de aviacao'],
    category: 'meio_ambiente',
    ministries: ['agricultura', 'infraestrutura'],
    baseCost: 13e9,
    instrument: 'projeto_lei',
    legalRisk: 18,
    months: 30,
    label: 'biocombustíveis avançados',
    expand: {
      primaryBalance: -13,
      environmentIndex: 0.9,
      gdpGrowth: 0.08,
      inflation: -0.04,
    },
    winners: [
      { groupId: 'agronegocio', delta: 3, reason: 'Cana e milho ganham destino industrial com preço melhor.' },
      { groupId: 'ambientalistas', delta: 1.4, reason: 'Combustível com pegada menor que o fóssil.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -1.6, reason: 'Mais um subsídio setorial permanente.' },
      { groupId: 'baixa_renda', delta: -1.2, reason: 'Terra para combustível é terra que não produz comida.' },
    ],
  },
  {
    id: 'baterias_nacionais',
    specificity: 2.1,
    keywords: ['baterias', 'fabricacao de baterias', 'reciclagem de baterias', 'litio'],
    category: 'economia',
    ministries: ['infraestrutura', 'fazenda'],
    baseCost: 16e9,
    instrument: 'programa',
    legalRisk: 18,
    months: 36,
    label: 'cadeia nacional de baterias',
    expand: {
      primaryBalance: -16,
      gdpGrowth: 0.09,
      environmentIndex: 0.7,
      businessConfidence: 2.2,
    },
    winners: [
      { groupId: 'empresariado', delta: 2.6, reason: 'Fabricar em vez de importar célula pronta.' },
      { groupId: 'trabalhadores', delta: 1.8, reason: 'Emprego industrial de média e alta tecnologia.' },
      { groupId: 'ambientalistas', delta: 1.2, reason: 'Bateria reciclada não vira passivo químico.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -2, reason: 'Política industrial cara para competir com escala chinesa.' },
      { groupId: 'indigenas', delta: -1.4, reason: 'Lítio está onde já há conflito de terra.' },
    ],
  },

  // -------------------------------------------------------------------------
  // Tecnologia e futuro
  // -------------------------------------------------------------------------
  {
    id: 'inteligencia_artificial',
    specificity: 1.9,
    keywords: [
      'inteligencia artificial', 'programa nacional de inteligencia artificial',
      'especialistas em inteligencia artificial', 'automatizar servicos publicos',
    ],
    category: 'economia',
    ministries: ['infraestrutura', 'educacao'],
    baseCost: 18e9,
    instrument: 'programa',
    legalRisk: 20,
    months: 30,
    label: 'política nacional de inteligência artificial',
    expand: {
      primaryBalance: -18,
      gdpGrowth: 0.12,
      educationIndex: 0.8,
      businessConfidence: 3,
      corruptionPerception: 0.6,
    },
    winners: [
      { groupId: 'universitarios', delta: 3.2, reason: 'Formação e bolsa na área que mais contrata.' },
      { groupId: 'empresariado', delta: 2.6, reason: 'Produtividade e serviço público mais barato de acessar.' },
    ],
    losers: [
      { groupId: 'trabalhadores', delta: -2.4, reason: 'Automação chega primeiro no trabalho repetitivo.' },
      { groupId: 'servidores', delta: -1.8, reason: 'Automatizar serviço público é reduzir posto de trabalho público.' },
    ],
  },
  {
    id: 'supercomputacao',
    specificity: 2.1,
    keywords: [
      'supercomputa', 'computacao de alto desempenho', 'computacao em nuvem', 'nuvem soberana',
      'data center nacional',
    ],
    category: 'economia',
    ministries: ['infraestrutura', 'educacao'],
    baseCost: 12e9,
    instrument: 'programa',
    legalRisk: 16,
    months: 30,
    label: 'infraestrutura nacional de computação',
    expand: {
      primaryBalance: -12,
      educationIndex: 0.7,
      gdpGrowth: 0.07,
      businessConfidence: 1.8,
    },
    winners: [
      { groupId: 'universitarios', delta: 3.4, reason: 'Pesquisa que hoje depende de servidor alugado no exterior.' },
      { groupId: 'empresariado', delta: 1.6, reason: 'Capacidade de processamento nacional e mais barata.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -1.8, reason: 'Investimento pesado num setor em que o privado já opera.' },
      { groupId: 'ambientalistas', delta: -1.2, reason: 'Data center consome energia e água em escala.' },
    ],
  },
  {
    id: 'ciberseguranca',
    specificity: 2,
    keywords: ['ciberseguranca', 'seguranca cibernetica', 'ataque hacker', 'protecao de infraestrutura critica'],
    category: 'seguranca',
    ministries: ['defesa', 'justica'],
    baseCost: 10e9,
    instrument: 'programa',
    legalRisk: 18,
    months: 24,
    label: 'cibersegurança nacional',
    expand: {
      primaryBalance: -10,
      securityIndex: 1.5,
      businessConfidence: 2.2,
      corruptionPerception: 0.6,
    },
    winners: [
      { groupId: 'militares', delta: 2.6, reason: 'Defesa cibernética virou fronteira de verdade.' },
      { groupId: 'empresariado', delta: 2.2, reason: 'Ataque a sistema bancário e a rede elétrica para o país.' },
      { groupId: 'classe_media', delta: 1.4, reason: 'Dado pessoal e serviço público protegidos.' },
    ],
    losers: [
      { groupId: 'universitarios', delta: -1.2, reason: 'Estrutura de vigilância cresce junto com a de proteção.' },
    ],
  },
  {
    id: 'robotica_pesquisa',
    specificity: 2,
    keywords: ['robotica', 'centro de pesquisa em robotica', 'automacao industrial'],
    category: 'economia',
    ministries: ['educacao', 'infraestrutura'],
    baseCost: 9e9,
    instrument: 'programa',
    legalRisk: 14,
    months: 30,
    label: 'pesquisa em robótica e automação',
    expand: {
      primaryBalance: -9,
      gdpGrowth: 0.07,
      educationIndex: 0.6,
      businessConfidence: 1.6,
    },
    winners: [
      { groupId: 'universitarios', delta: 2.8, reason: 'Laboratório com financiamento estável.' },
      { groupId: 'empresariado', delta: 2, reason: 'Automação nacional custa menos que linha importada.' },
    ],
    losers: [
      { groupId: 'trabalhadores', delta: -2.2, reason: 'Robô na linha de produção é posto de trabalho a menos.' },
    ],
  },
  {
    id: 'semicondutores',
    specificity: 2.2,
    keywords: ['semicondutor', 'chips', 'fabrica de chips', 'microchip', 'fabricar chips'],
    category: 'economia',
    ministries: ['infraestrutura', 'fazenda'],
    baseCost: 38e9,
    instrument: 'projeto_lei',
    legalRisk: 22,
    months: 48,
    label: 'produção nacional de semicondutores',
    expand: {
      primaryBalance: -38,
      gdpGrowth: 0.11,
      businessConfidence: 2.8,
      countryRisk: -4,
      fiscalCredibility: -2.4,
    },
    winners: [
      { groupId: 'empresariado', delta: 2.8, reason: 'Cadeia eletrônica inteira depende de chip importado hoje.' },
      { groupId: 'universitarios', delta: 2.4, reason: 'Microeletrônica volta a ter destino profissional no país.' },
      { groupId: 'militares', delta: 1.6, reason: 'Componente crítico deixa de depender de fornecedor estrangeiro.' },
    ],
    losers: [
      { groupId: 'mercado_financeiro', delta: -3, reason: 'Fábrica de chip é a aposta industrial mais cara que existe, e o Brasil já tentou antes.' },
      { groupId: 'classe_media', delta: -1, reason: 'Subsídio bilionário a um setor que emprega pouca gente.' },
    ],
  },
  {
    id: 'agencia_espacial',
    specificity: 2.1,
    keywords: ['exploracao espacial', 'programa espacial', 'satelites', 'agencia espacial', 'alcantara'],
    category: 'institucional',
    ministries: ['defesa', 'educacao'],
    baseCost: 14e9,
    instrument: 'projeto_lei',
    legalRisk: 18,
    months: 42,
    label: 'programa espacial brasileiro',
    expand: {
      primaryBalance: -14,
      businessConfidence: 1.2,
      educationIndex: 0.5,
      infrastructureIndex: 0.6,
    },
    winners: [
      { groupId: 'militares', delta: 3.2, reason: 'Satélite próprio é soberania de comunicação e de observação.' },
      { groupId: 'universitarios', delta: 2.6, reason: 'Engenharia aeroespacial com programa de verdade.' },
    ],
    losers: [
      { groupId: 'baixa_renda', delta: -2, reason: 'Foguete enquanto falta remédio no posto é a comparação que sempre aparece.' },
      { groupId: 'mercado_financeiro', delta: -2.2, reason: 'Retorno econômico incerto e prazo longo demais.' },
    ],
  },
];
